title: Inazira Skin Care
description: Skincare tips, ingredient guides, and routines from INAZIRA.
url: "https://skincare.inazira.com"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 6
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
